[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
#Content-Security-Policy = "default-src 'self' https://unpkg.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; connect-src 'self' https://unpkg.com; worker-src 'self' blob:; img-src 'self' data:; frame-src 'self';"
